# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FG4WRzB4PJe4LRal7ZkI415YKB80jYCI
"""

print("hello world")

a = 10
type(a)

a = "hello"
type(a)

a

print('''

 
        
(\_/)
( •,•)
(")_(")
      
      ''')

print("What we think\
 we became")

print("hello\t everyone")

print("hello\a everyone")

print ("\a")

marks = 10
name = "Siva"
age = 22
print ("The marks of ", name, "are ", marks, "and age is ", age)

marks = 10.905
name = "Siva"
age = 22
print ("The marks of %s are %.2f and age is %d"%(name,marks,age))

marks = 10.905
name = "Siva"
age = 22
print (f"the marks of {name} is {marks} and age is {age}")

print('python\'s world')

int
float
string
tuple
list
dictionary
set
boolean
(data types)

a = ""
dir(a)

a = "HEY I AM AAZIN MUHAMMED"
a.lower()

mutable = list, set, dict
immutable = strng, tuple, int, float

str1 = "sathyameva jayate"
str1

id(str1)

a = str1

id(a)

str1 = "hello"

id(str1)

str1 = "welcome my python"
str1.replace("my","to")

str1

a

list1 = []
dir(list1)



